// METEOR // PROTOCOL — 超軽量バンドラ（依存なし）
// ES モジュール群を1つのクラシックスクリプトに結合し、file:// でも動くようにする。
//   実行: node build.js  → js/meteor.bundle.js を生成
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const stripImports = (s) => s.replace(/^\s*import\b[^\n]*\n/gm, '');
const stripExport = (s) => s.replace(/\bexport\s+(?=(const|class|function|let|var)\b)/g, '');

// 結合順（依存順）。すべて同一IIFEスコープに展開する。
const FILES = [
  'js/core/palette.js',
  'js/core/audio.js',
  'js/core/storage.js',
  'js/core/engine.js',
  'js/title.js',
  'js/game.js',
  'js/main.js',
];

let out = '// === METEOR // PROTOCOL bundle (auto-generated by build.js — do not edit) ===\n';
out += '(function(){\n"use strict";\n';
for (const f of FILES) {
  out += `\n// ---- ${f} ----\n`;
  out += stripExport(stripImports(read(f))) + '\n';
}
out += '})();\n';

const dest = 'js/meteor.bundle.js';
fs.writeFileSync(path.join(ROOT, dest), out, 'utf8');
console.log('built ' + dest + ' (' + out.length + ' bytes)');
