// 開発用の超軽量バンドラ（依存なし）。
// ES モジュール群を1つのクラシックスクリプトに結合し、file:// でも動くようにする。
//   実行: node build.js  → js/microarcade.bundle.js を生成
//
// 仕組み:
//  - 全体を1つのIIFEで包む（グローバルを汚さない）。
//  - core/menu はそのスコープ直下に展開（import除去・export除去）。
//  - 各ゲームは衝突する内部const（COLS等）を持つので、個別IIFEで包み __games に登録。
//  - main.js のブートストラップを取り込み、GAMES配列を __games に差し替える。
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

// import 行を除去
const stripImports = (s) => s.replace(/^\s*import\b[^\n]*\n/gm, '');
// 先頭の export キーワードのみ除去（export const/class/function → const/class/function）
const stripExport = (s) => s.replace(/\bexport\s+(?=(const|class|function|let|var)\b)/g, '');

const CORE = [
  'js/core/palette.js',
  'js/core/audio.js',
  'js/core/storage.js',
  'js/core/engine.js',
  'js/menu.js',
];
// メニュー表示順
const GAMES = [
  'js/games/rogue.js',
  'js/games/binary.js',
  'js/games/hack.js',
  'js/games/snake.js',
  'js/games/beeper.js',
  'js/games/fire.js',
  'js/games/meteor.js',
  'js/games/lander.js',
];

let out = '';
out += '// === MICRO ARCADE bundle (auto-generated by build.js — do not edit) ===\n';
out += '(function(){\n"use strict";\nvar __games = [];\n';

// core + menu をスコープ直下に展開
for (const f of CORE) {
  out += `\n// ---- ${f} ----\n`;
  out += stripExport(stripImports(read(f))) + '\n';
}

// 各ゲームは個別IIFEで包んで __games に登録（内部constの衝突を防ぐ）
for (const f of GAMES) {
  const body = stripExport(stripImports(read(f)));
  out += `\n// ---- ${f} ----\n`;
  out += '(function(){\n' + body + '\n;__games.push({ meta: meta, Game: Game });\n})();\n';
}

// main.js のブートストラップ（importを除去し、GAMES を __games に差し替え）
let main = stripImports(read('js/main.js'));
main = main.replace(/const\s+GAMES\s*=[\s\S]*?;\s*\n/, 'const GAMES = __games;\n');
out += `\n// ---- js/main.js (bootstrap) ----\n` + main + '\n';

out += '})();\n';

const dest = 'js/microarcade.bundle.js';
fs.writeFileSync(path.join(ROOT, dest), out, 'utf8');
console.log('built ' + dest + ' (' + out.length + ' bytes)');
